fix: switch to slf4j-simple
The previous slf4j implementation failed the dependency analysis:
  [INFO] --- dependency:3.8.1:analyze-only (analyze) @ spring-boot-starter-camunda-test-testcontainer ---
  Error:  Unused declared dependencies found:
  Error:     org.apache.logging.log4j:log4j-slf4j2-impl:jar:2.23.1:test

We can easily replace it with slf4j-simple, as this is used in all other
places for tests in ZPT.